name: Latest blog post workflow
on:
  #schedule:
    # Runs every hour
    #- cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: The-R4V3N/blog-post-workflow@master
        with:
          feed_list: 'https://dev.to/feed/ther4v3n'
          template: "<tr><td>$title</td><td>$url</td></tr>"
