name: Latest blog post workflow
on:
  schedule:
     # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://www.oliver-joisten.se/feed/'
          template: "<tr><td>$title</td><td>$url</td></tr>"
      - name: Add line breaks after blog post links
        run: |
          sed -i -e 's/\(\[.*\]\)(\(http.*\))/\1\n\n\2/' README.md
