name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: The-R4V3N/The-R4V3N@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          COMMIT_BY_ME: "TRUE"
          COMMIT_USERNAME: "The-R4V3N"
          SHOW_UPDATED_DATE: "TRUE"
          UPDATED_DATE_FORMAT: "%d/%m/%Y"
          SHOW_LINES_OF_CODE: "TRUE"
          
          
          
          
